import {
  createContext,
  useContext,
  useState,
  useCallback,
  ReactNode,
} from "react";

export type Lang = "fa" | "en";

const translations = {
  // Index page
    turnTimeLimit: {
    fa: "محدودیت زمان نوبت",
    en: "Turn Time Limit",
  },
      numberOfPlayers: {
    fa: "تعداد بازیکنان",
    en: "NUMBER OF PLAYERS",
  },
    leaguesAndEventsTitle: { fa: "لیگ‌ها و رویدادها", en: "Leagues & Events" },
  currentSeasonTitle: { fa: "فصل سوم: نبرد سنگ‌ها", en: "Season 3: Clash of Gems" },
  currentSeasonDesc: { fa: "با پیروزی در مسابقات رتبه‌بندی (Ranked)، امتیاز کسب کنید و به لیگ‌های بالاتر صعود کنید.", en: "Win ranked matches to earn MMR and climb to higher leagues." },
  
  tierOnyxDesc: { fa: "شروع مسیر", en: "The beginning of the journey" },
  tierEmerald: { fa: "لیگ زمرد (Emerald)", en: "Emerald League" },
  tierEmeraldDesc: { fa: "بازیکنان در حال پیشرفت", en: "Progressing players" },
  tierSapphire: { fa: "لیگ یاقوت کبود (Sapphire)", en: "Sapphire League" },
  tierSapphireDesc: { fa: "استراتژیست‌های ماهر", en: "Skilled strategists" },
  tierRuby: { fa: "لیگ یاقوت سرخ (Ruby)", en: "Ruby League" },
  tierRubyDesc: { fa: "بازیکنان حرفه‌ای", en: "Professional players" },
  tierDiamond: { fa: "لیگ الماس (Diamond)", en: "Diamond League" },
  tierDiamondDesc: { fa: "نخبگان اسپلندور", en: "Splendor elites" },
  tierNoble: { fa: "اشراف‌زاده (Noble)", en: "Noble (Top 100)" },
  tierNobleDesc: { fa: "۱۰۰ بازیکن برتر جهان", en: "Top 100 players worldwide" },

  eventBlitzDesc: { fa: "فقط ۱۵ ثانیه زمان برای هر نوبت! سرعت تصمیم‌گیری خود را محک بزنید.", en: "Only 15 seconds per turn! Test your quick thinking." },
  endsIn2Days: { fa: "پایان در ۲ روز", en: "Ends in 2 days" },
  
  eventMarathonDesc: { fa: "شرط پیروزی رسیدن به ۲۱ امتیاز است. موتور اقتصادی خود را بسازید!", en: "Win condition is 21 points. Build your economic engine!" },
  endsIn5Days: { fa: "پایان در ۵ روز", en: "Ends in 5 days" },
  
  eventRichStart: { fa: "شروع ثروتمندانه", en: "Rich Start" },
  eventRichStartDesc: { fa: "بازی را با یک توکن از هر رنگ آغاز کنید.", en: "Start the game with one token of each color." },
  endsIn12Hours: { fa: "پایان در ۱۲ ساعت", en: "Ends in 12 hours" },
    // ==========================================
  // متغیرهای مربوط به لیگ‌ها (tier.titleKey و tier.descKey)
  // ==========================================
  tierOnyx: { fa: "لیگ عقیق (Onyx)", en: "Onyx League" },

  // ==========================================
  // متغیرهای مربوط به رویدادها (event.titleKey, event.descKey, event.timeKey)
  // ==========================================
  eventBlitz: { fa: "اسپلندور سرعتی (Blitz)", en: "Blitz Splendor" },

  eventKnockout: { fa: "تورنمنت حذفی", en: "Knockout Tournament" },
  eventKnockoutDesc: { fa: "براکت ۸ نفره. برنده تمام جوایز را می‌برد!", en: "8-player bracket. Winner takes all!" },
  startsIn2Hours: { fa: "شروع در ۲ ساعت", en: "Starts in 2 hours" },

  // ==========================================
  // متغیرهای مربوط به چالش‌ها (challenge.titleKey, challenge.descKey, challenge.rewardKey)
  // ==========================================
  soloPuzzle: { fa: "پازل روزانه", en: "Daily Puzzle" },
  soloPuzzleDesc: { fa: "با استفاده از توکن‌های داده شده، در یک حرکت به ۱۵ امتیاز برسید.", en: "Reach 15 points in one move using the given tokens." },
  rewardCoins: { fa: "۵۰۰ سکه", en: "500 Coins" },

  soloSurvival: { fa: "بقا در برابر ربات‌ها", en: "Bot Survival" },
  soloSurvivalDesc: { fa: "سه ربات با درجات سختی مختلف را پشت سر هم شکست دهید.", en: "Defeat three bots of varying difficulty in a row." },
  rewardCardBack: { fa: "پشت‌کارت اختصاصی", en: "Exclusive Card Back" },

  soloTurnLimit: { fa: "چالش محدودیت دور", en: "Turn Limit Challenge" },
  soloTurnLimitDesc: { fa: "بازی را در کمتر از ۲۵ راند به پایان برسانید.", en: "Finish the game in less than 25 rounds." },
  rewardBorder: { fa: "قاب پروفایل رعد", en: "Lightning Border" },

  tabSeason: { fa: "فصل جاری", en: "Current Season" },
  tabEvents: { fa: "رویدادهای زنده", en: "Live Events" },
  tabSolo: { fa: "چالش‌های تک‌نفره", en: "Solo Challenges" },
  eventMarathon: { fa: "ماراتن (۲۱ امتیازی)", en: "Marathon (21 Points)" },

  subtitle: {
    fa: "تجارت جواهرات در دوران رنسانس",
    en: "Gem Trading in the Renaissance",
  },
    shareCode: {
    fa: "اشتراک‌گذاری کد",
    en: "Share code",
  },
   playersCount: {
    fa: "{{count}} نفره",
    en: "{{count}} players",
  },
  createRoomHint: {
    fa: "یک اتاق جدید بساز و کد را برای دوستانت بفرست.",
    en: "Create a new room and send the code to your friends.",
  },
  joinRoomHint: {
    fa: "کدی که دوستت فرستاده را وارد کن تا به اتاق او ملحق شوی.",
    en: "Enter your friend's room code to join their game.",
  },
  or: {
    fa: "یا",
    en: "OR",
  },
  shareCodeHelper: {
    fa: "این کد را برای دوستانت بفرست تا بتوانند تو را اضافه کنند.",
    en: "Share this code so friends can add you.",
  },
  // متن ثابت برای share (بدون پارامتر دوم)
  shareUserCodeText: {
    fa: "این کد من در بازی اسپلندور آنلاین است. برای اضافه کردن من به دوستان، این کد را در بخش دوستان وارد کن.",
    en: "This is my Splendor Online code. Use it in the Friends section to add me.",
  },
  
  playWithAI: { fa: "بازی با ربات", en: "Play vs AI" },
  playWithAIDesc: { fa: "بازی هوشمند با AI", en: "Challenge the computer" },
  localPlay: { fa: "بازی محلی", en: "Local Play" },
  localPlayDesc: {
    fa: "بازی با دوستان روی یک دستگاه",
    en: "Play with friends on one device",
  },
   choosePlayersAndStart: {
    fa: "تعداد بازیکن‌ها را انتخاب کن و بازی را شروع کن.",
    en: "Choose the number of players and start the game.",
  },
  gameSummary: {
    fa: "خلاصه بازی",
    en: "Game Summary",
  },

  previewGroupName: {
    fa: "نام نمونه گروه",
    en: "Group Preview Name",
  },
  previewGroupDescription: {
    fa: "توضیحات گروه شما اینجا نمایش داده می‌شود.",
    en: "Your group description will appear here.",
  },
  membersCountLabel: {
    fa: "تعداد اعضا",
    en: "Members",
  },
  copiedLabel: {
    fa: "کپی شد",
    en: "Copied",
  },
  groupIsFull: {
    fa: "گروه پر است",
    en: "Group is full",
  },
  ourRankLabel: {
    fa: "رتبه گروه ما",
    en: "Our Group Rank",
  },

  mode: {
    fa: "حالت",
    en: "Mode",
  },
  onlinePlay: { fa: "بازی آنلاین", en: "Online Play" },
  onlinePlayDesc: {
    fa: "بازی با بازیکنان سراسر جهان",
    en: "Play with players worldwide",
  },
       "loginSubtitle":{ fa:"به انجمن بازرگانان خوش آمدید", en: "welcome to the splendor guilds"},
    signupSubtitle: {
    fa: "به انجمن بازرگانان ملحق شو و شهرتت را بساز.",
    en: "Join the guild of merchants and build your prestige.",
  },
  passwordHint: {
    fa: "حداقل ۸ کاراکتر، شامل یک عدد و یک علامت.",
    en: "At least 8 characters, including a number and a symbol.",
  },
  passwordsDoNotMatch: {
    fa: "رمزهای عبور یکسان نیستند.",
    en: "Passwords do not match.",
  },

  playerCount: { fa: "تعداد بازیکنان", en: "PLAYERS" },
  difficulty: { fa: "سطح سختی", en: "DIFFICULTY" },
  easy: { fa: "آسان", en: "Easy" },
  easyDesc: { fa: "ربات تصادفی و ساده", en: "Simple random bot" },
  medium: { fa: "متوسط", en: "Medium" },
  mediumDesc: { fa: "ربات منطقی و متعادل", en: "Smart and balanced bot" },
  hard: { fa: "سخت", en: "Hard" },
  hardDesc: { fa: "ربات استراتژیک و قوی", en: "Strategic and powerful bot" },
  startGame: { fa: "🎮 شروع بازی", en: "🎮 Start Game" },
  enterLobby: { fa: "🌐 ورود به لابی", en: "🌐 Enter Lobby" },
  tutorial: { fa: " آموزش بازی", en: " How to Play" },
  tutorialDesc: {
    fa: "قوانین و راهنمای بازی را یاد بگیرید",
    en: "Learn the rules and game guide",
  },
  attribution: {
    fa: "الهام گرفته از بازی رومیزی مارک آندره",
    en: "Inspired by the board game by Marc André",
  },
  settings: { fa: "تنظیمات", en: "Settings" },
  settingsDescription: {
    fa: "زبان و گزینه‌های صدا را تغییر دهید",
    en: "Change language and audio options",
  },
  language: { fa: "زبان", en: "Language" },
  english: { fa: "انگلیسی", en: "English" },
  persian: { fa: "فارسی", en: "Persian" },
  totalPlayers: { fa: "کل بازیکنان", en: "TOTAL PLAYERS" },
  humanPlayers: { fa: "بازیکنان انسانی", en: "HUMAN PLAYERS" },
  botPlayers: { fa: "ربات‌ها", en: "BOTS" },
  botDifficulty: { fa: "سختی ربات‌ها", en: "BOT DIFFICULTY" },
  pointsLabel: { fa: "امتیاز", en: "Points" },
  coinsLabel: { fa: "سکه", en: "Coins" },
  level: { fa: "مرحله", en: "Level" },
  levelUpTitle: { fa: "تبریک!", en: "Congratulations!" },
  levelUpMessage: { fa: "شما به مرحله رسیدید", en: "You reached level" },
  continueLabel: { fa: "ادامه", en: "Continue" },
  localPlayersHelp: {
    fa: "تعداد کل بازیکنان و تعداد ربات‌ها را انتخاب کنید.",
    en: "Choose the total players and how many should be bots.",
  },
  startLocalGame: { fa: "🎮 شروع بازی محلی", en: "🎮 Start Local Game" },
  bot: { fa: "ربات", en: "Bot" },

  // Game page
  player: { fa: "بازیکن", en: "Player" },
  aiThinking: { fa: "🤖 ربات در حال فکر...", en: "🤖 AI is thinking..." },
  botTurn: { fa: "نوبت ربات", en: "Bot Turn" },
  reserved: { fa: "رزرو شده", en: "Reserved" },
  tooManyTokens: {
    fa: "توکن‌های اضافی! برای برگرداندن کلیک کنید",
    en: "Too many tokens! Click to return",
  },
  nobles: { fa: "شاهزاده‌ها", en: "Nobles" },
  take: { fa: "برداشتن", en: "Take" },
  takeSame: { fa: "برداشتن دو سنگ یکسان", en: "Take 2 Same" },
  cancel: { fa: "انصراف", en: "Cancel" },
  purchase: { fa: "خرید", en: "Purchase" },
  reserve: { fa: "رزرو + سکه طلا", en: "Reserve + gold coin" },
  wins: { fa: "برنده شد!", en: "Wins!" },
  score: { fa: "امتیاز", en: "Score" },
  playAgain: { fa: "بازی مجدد", en: "Play Again" },
  menu: { fa: "منو", en: "Menu" },
  pts: { fa: "امتیاز", en: "pts" },
  quickRulesTitle: { fa: "خلاصه قوانین", en: "Quick Rules" },
  quickRulesSubtitle: {
    fa: "مرور سریع قوانین اصلی بازی",
    en: "A quick summary of the core rules",
  },
  quickRulesObjective: {
    fa: "هدف: رسیدن به ۱۵ امتیاز اعتبار.",
    en: "Objective: reach 15 prestige points.",
  },
  quickRulesTurn: {
    fa: "در نوبت خود یکی را انجام بده: برداشتن ۳ سنگ متفاوت یا ۲ سنگ یکسان (اگر ۴+ موجود باشد) یا خرید کارت.",
    en: "On your turn: take 3 different tokens or 2 of the same (if 4+ are available), or buy a card.",
  },
  quickRulesTokens: {
    fa: "حداکثر ۱۰ سنگ می‌توان نگه داشت؛ اضافه را قبل از پایان نوبت برگردان.",
    en: "You can hold at most 10 tokens. Return extras before ending your turn.",
  },
  quickRulesReserve: {
    fa: "رزرو کارت: یک کارت را رزرو کن و اگر طلا موجود بود، یک طلا بگیر.",
    en: "Reserve: reserve one card and take a gold token if available.",
  },
  quickRulesNobles: {
    fa: "اشراف‌زادگان با داشتن پاداش‌های کافی به‌صورت خودکار می‌آیند.",
    en: "Nobles visit automatically when you have enough bonuses.",
  },
  quickRulesWin: {
    fa: "رسیدن به ۱۵ امتیاز دور آخر را فعال می‌کند؛ بیشترین امتیاز برنده است.",
    en: "Reaching 15 points triggers the final round; highest score wins.",
  },
  quickRulesClose: { fa: "بازگشت به بازی", en: "Back to Game" },

  // Tutorial page
  tutorialTitle: { fa: " آموزش بازی", en: " How to Play" },
  stepByStep: { fa: "آموزش مرحله به مرحله", en: "Step by Step Tutorial" },
  stepByStepDesc: {
    fa: "یادگیری قوانین بازی به صورت تعاملی",
    en: "Learn the rules interactively",
  },
  youtubeTitle: { fa: "آموزش در یوتیوب", en: "YouTube Tutorials" },
  youtubeDesc: {
    fa: "ویدیوهای آموزشی در YouTube",
    en: "Video tutorials on YouTube",
  },
  aparatTitle: { fa: "آموزش در آپارات", en: "Aparat Tutorials" },
  aparatDesc: { fa: "ویدیوهای آموزشی فارسی", en: "Persian video tutorials" },
  prev: { fa: "← قبلی", en: "← Previous" },
  back: { fa: "← بازگشت", en: "← Back" },
  next: { fa: "بعدی →", en: "Next →" },
  startPlaying: { fa: "🎮 شروع بازی", en: "🎮 Start Playing" },

  // Tutorial steps
  tut1Title: { fa: "هدف بازی", en: "Game Objective" },
  tut1Content: {
    fa: "هدف شما جمع‌آوری ۱۵ امتیاز منزلت است. امتیازات از خرید کارت‌های توسعه و دیدار با شاهزاده‌ها بدست می‌آید.",
    en: "Your goal is to collect 15 prestige points. Points come from purchasing development cards and visiting nobles.",
  },
  tut1Tip: {
    fa: "اولین بازیکنی که به ۱۵ امتیاز برسد، دور آخر را فعال می‌کند.",
    en: "The first player to reach 15 points triggers the final round.",
  },
  tut2Title: { fa: "توکن‌های جواهر", en: "Gem Tokens" },
  tut2Content: {
    fa: "در هر نوبت می‌توانید ۳ توکن از رنگ‌های مختلف بردارید، یا ۲ توکن از یک رنگ (اگر حداقل ۴ عدد از آن رنگ موجود باشد).",
    en: "Each turn you can take 3 tokens of different colors, or 2 tokens of the same color (if at least 4 of that color are available).",
  },
  tut2Tip: {
    fa: "حداکثر ۱۰ توکن می‌توانید داشته باشید. اگر بیشتر شد باید برگردانید.",
    en: "You can hold at most 10 tokens. If you have more, you must return some.",
  },
  tut3Title: { fa: "خرید کارت", en: "Buying Cards" },
  tut3Content: {
    fa: "با پرداخت توکن‌های لازم، کارت توسعه بخرید. هر کارت یک امتیاز ویژه (تخفیف دائمی) به شما می‌دهد.",
    en: "Pay the required tokens to buy a development card. Each card gives you a permanent gem bonus (discount).",
  },
  tut3Tip: {
    fa: "امتیازات ویژه مثل تخفیف عمل می‌کنند و خرید کارت‌های بعدی را ارزان‌تر می‌کنند.",
    en: "Gem bonuses act as discounts, making future cards cheaper.",
  },
  tut4Title: { fa: "رزرو کارت", en: "Reserving Cards" },
  tut4Content: {
    fa: "می‌توانید یک کارت را رزرو کنید تا بعداً بخرید. با رزرو یک توکن طلا (جوکر) هم دریافت می‌کنید.",
    en: "You can reserve a card to buy later. Reserving also gives you a gold (wild) token.",
  },
  tut4Tip: {
    fa: "حداکثر ۳ کارت می‌توانید رزرو داشته باشید. توکن طلا جایگزین هر رنگی می‌شود.",
    en: "You can reserve up to 3 cards. Gold tokens can substitute any color.",
  },
  tut5Title: { fa: "شاهزاده‌ها", en: "Nobles" },
  tut5Content: {
    fa: "وقتی امتیازات ویژه کافی جمع کنید، شاهزاده خودکار به شما سر می‌زند و ۳ امتیاز منزلت می‌گیرید.",
    en: "When you have enough gem bonuses, a noble automatically visits you, granting 3 prestige points.",
  },
  tut5Tip: {
    fa: "دیدار با شاهزاده فقط با امتیازات ویژه (کارت‌ها) ممکن است، نه با توکن‌ها.",
    en: "Noble visits are based on card bonuses only, not tokens.",
  },

  // Complete Manual / دستورالعمل کامل
  fullManual: { fa: "دستورالعمل کامل بازی", en: "Complete Game Manual" },
  fullManualDesc: {
    fa: "تمام قوانین و توضیحات بازی را بخوانید",
    en: "Read all game rules and details",
  },
  gameRules: { fa: "قوانین بازی", en: "Game Rules" },
  setupSection: { fa: "تنظیم بازی", en: "Game Setup" },
  setupContent: {
    fa: "بازی با ۲ تا ۴ بازیکن بازی می‌شود. هر بازیکن یک صفحه نمایش و ۰ توکن شروع می‌کند. توکن‌های جواهر (۵ رنگ مختلف) و توکن‌های طلا در وسط میز قرار می‌گیرند.",
    en: "The game is played with 2-4 players. Each player gets a board and starts with 0 tokens. Gem tokens and gold tokens are placed in the center.",
  },
  turnSection: { fa: "نوبت بازی", en: "Turn Sequence" },
  turnContent: {
    fa: "در هر نوبت، بازیکن یکی از این اعمال را انجام می‌دهد:\n1. توکن بردار: ۳ رنگ مختلف یا ۲ از یک رنگ\n2. کارت بخر: توکن‌های لازم را بپرداخت و یک کارت بخر\n3. کارت رزرو کن: یک کارت را برای بعد رزرو کن و ۱ توکن طلا بگیر",
    en: "On your turn, choose one action:\n1. Take Tokens: Take 3 different or 2 of the same color\n2. Buy Card: Pay required tokens and purchase a development card\n3. Reserve Card: Reserve a card for later and take a gold token",
  },
  cardTypesSection: { fa: "انواع کارت‌ها", en: "Card Types" },
  cardTypesContent: {
    fa: "کارت‌های سطح ۱: ارزان و کم امتیاز\nکارت‌های سطح ۲: متوسط قیمت و امتیاز\nکارت‌های سطح ۳: گران و بیشترین امتیاز",
    en: "Level 1 Cards: Cheap, low points\nLevel 2 Cards: Medium cost and points\nLevel 3 Cards: Expensive, highest points",
  },
  tokenRulesSection: { fa: "قوانین توکن", en: "Token Rules" },
  tokenRulesContent: {
    fa: "حداکثر ۱۰ توکن می‌توانید نگه دارید\nتوکن‌های طلا جایگزین هر رنگی می‌شوند\nپس از هر خریدِ کارت، امتیازاتِ آن کارت برای همیشه دریافت می‌کنید",
    en: "Maximum 10 tokens per player\nGold tokens substitute any color\nCard bonuses are permanent and stack",
  },
  winConditionSection: { fa: "شرط پیروزی", en: "Winning the Game" },
  winConditionContent: {
    fa: "اولین بازیکنی که به ۱۵ امتیازِ منزلت برسد، دور نهایی را مشخص می‌کند. دور نهایی ادامه می‌یابد تا همه بازیکنان یک نوبت دیگر را کامل کنند. بازیکنی که بیشترین امتیاز را داشته باشد، برنده است.",
    en: "The first player to reach 15 prestige points triggers the final round. The player with the most points after the final round wins.",
  },
  strategySection: { fa: "نکات استراتژیک", en: "Strategic Tips" },
  strategyContent: {
    fa: "• سعی کنید امتیازاتِ ویژه را جمع کنید قبل از شاهزاده‌ها\n• توکن‌های طلا محدود هستند، احتیاط کنید\n• کارت‌های سطح بالا بیشتر امتیاز می‌دهند اما سفت‌تر است\n• میتوانید رقبای خود را مسدود کنید با کارت‌های خاص",
    en: "• Build gem bonuses to attract nobles\n• Gold tokens are limited, use wisely\n• Higher level cards give more points but are expensive\n• Strategic card reservations block opponents",
  },

  // Sound and Audio / صدا و موسیقی
  soundSettings: { fa: "تنظیمات صدا", en: "Sound Settings" },
  backgroundMusic: { fa: "موسیقی پس‌زمینه", en: "Background Music" },
  soundEffects: { fa: "جلوه‌های صوتی", en: "Sound Effects" },
  enableAudio: { fa: "فعال کردن", en: "Enable" },
  disableAudio: { fa: "غیرفعال کردن", en: "Disable" },

  // Gem Names / نام سنگ‌های قیمتی
  cost: { fa: "قیمت", en: "Cost" },
  ruby: { fa: "یاقوت", en: "Ruby" },
  sapphire: { fa: "یاقوت کبود", en: "Sapphire" },
  emerald: { fa: "زمرد", en: "Emerald" },
  diamond: { fa: "الماس", en: "Diamond" },
  onyx: { fa: "عقیق سیاه", en: "Onyx" },
  gold: { fa: "طلا (جوکر)", en: "Gold (Wild)" },

  // Online Chat / چت آنلاین
  chat: { fa: "چت", en: "Chat" },
  sendMessage: { fa: "ارسال پیام", en: "Send Message" },
  typeMessage: { fa: "پیام خود را بنویسید...", en: "Type your message..." },
  microphone: { fa: "میکروفون", en: "Microphone" },
  enableMicrophone: { fa: "روشن کردن میکروفون", en: "Turn on Microphone" },
  disableMicrophone: { fa: "خاموش کردن میکروفون", en: "Turn off Microphone" },

  // Online Game / بازی آنلاین
  onlineGameTitle: {
    fa: "بازی آنلاین | Online Game",
    en: "Online Game | بازی آنلاین",
  },
  createRoom: { fa: "ایجاد اتاق", en: "Create Room" },
  joinRoom: { fa: "پیوستن به اتاق", en: "Join Room" },
  roomId: { fa: "شناسه اتاق", en: "Room ID" },
  enterRoomId: { fa: "شناسه اتاق را وارد کنید...", en: "Enter Room ID..." },
  roomCreated: {
    fa: "✅ اتاق با موفقیت ایجاد شد!",
    en: "✅ Room created successfully!",
  },
  roomJoined: { fa: "✅ به اتاق پیوستید!", en: "✅ Joined room!" },
  waitingForPlayers: {
    fa: "⏳ در انتظار بازیکنان دیگر...",
    en: "⏳ Waiting for other players...",
  },
  playerJoined: { fa: "بازیکن پیوست:", en: "Player joined:" },
  playerLeft: { fa: "بازیکن ترک کرد:", en: "Player left:" },
  playerRemoved: { fa: "بازیکن حذف شد:", en: "Player removed:" },
  playerRemovedAfk: { fa: "به دلیل عدم فعالیت", en: "Removed for inactivity" },
  startingGame: { fa: "🎮 شروع بازی...", en: "🎮 Starting game..." },
  gameStarted: { fa: "🎮 بازی شروع شد!", en: "🎮 Game started!" },
  yourTurn: { fa: "🎯 نوبت شما است!", en: "🎯 Your turn!" },
  playerTurn: { fa: "نوبت بازیکن:", en: "Player's turn:" },
  connectionLost: { fa: "❌ ارتباط قطع شد!", en: "❌ Connection lost!" },
  reconnecting: { fa: "🔄 درحال اتصال مجدد...", en: "🔄 Reconnecting..." },
  connectionRestored: {
    fa: "✅ ارتباط برقرار شد!",
    en: "✅ Connection restored!",
  },
  errorConnecting: {
    fa: "❌ خطا در اتصال به سرور",
    en: "❌ Error connecting to server",
  },
  serverNotAvailable: {
    fa: "❌ سرور دستیاب نیست",
    en: "❌ Server not available",
  },
  noRoomFound: { fa: "❌ اتاق یافت نشد", en: "❌ Room not found" },
  roomFull: { fa: "❌ اتاق پر است", en: "❌ Room is full" },
  invalidRoomId: { fa: "❌ شناسه اتاق نامعتبر است", en: "❌ Invalid Room ID" },
  leaveRoom: { fa: "ترک اتاق", en: "Leave Room" },
  confirmLeave: {
    fa: "آیا مطمئن هستید که می‌خواهید ترک کنید؟",
    en: "Are you sure you want to leave?",
  },

  // Lobby / لابی
  lobbyTitle: { fa: "لابی آنلاین", en: "Online Lobby" },
  players: { fa: "بازیکنان", en: "Players" },
  maxPlayers: { fa: "حداکثر بازیکنان", en: "Max Players" },
  status: { fa: "وضعیت", en: "Status" },
  waiting: { fa: "در انتظار", en: "Waiting" },
  playing: { fa: "در حال بازی", en: "Playing" },
  finished: { fa: "پایان یافته", en: "Finished" },

  // Game Status / وضعیت بازی
  hostDisconnected: {
    fa: "⚠️ میزبان ارتباط قطع کرد",
    en: "⚠️ Host disconnected",
  },
  gameEnded: { fa: "🏁 بازی پایان یافت!", en: "🏁 Game ended!" },
  finalScores: { fa: "امتیازات نهایی:", en: "Final Scores:" },
  congratulations: {
    fa: "🎉 تبریک می‌گوییم! شما برنده شدید!",
    en: "🎉 Congratulations! You won!",
  },
  betterLuck: {
    fa: "💪 دفعه بعد بهتر خواهد شد!",
    en: "💪 Better luck next time!",
  },
  noPoints: { fa: "بدون امتیاز", en: "No Points" },
  leaveGameTitle: {
    fa: "آیا مطمئن هستید که می‌خواهید از بازی خارج شوید؟",
    en: "Are you sure you want to leave the game?",
  },
  leaveGameDescription: {
    fa: "بازی فعلی بسته می‌شود و به منو برمی‌گردید.",
    en: "Your current match will be closed and you will return to the menu.",
  },
  stay: { fa: "ماندن", en: "Stay" },
  leaveGameAction: { fa: "خروج از بازی", en: "Leave Game" },
  gameChatTitle: { fa: "چت بازی 💬", en: "💬 Game Chat" },
  noMessagesYet: { fa: "💭 هنوز پیامی ارسال نشده", en: "💭 No messages yet" },
  typeMessageShort: { fa: "پیام بنویسید...", en: "Type message..." },
  sendShort: { fa: "✉️ ارسال", en: "✉️ Send" },
  createRoomTitle: { fa: "📍 ایجاد اتاق", en: "📍 Create Room" },
  joinRoomTitle: { fa: "🔗 پیوستن به اتاق", en: "🔗 Join Room" },
  roomCode: { fa: "کد اتاق", en: "Room Code" },
  generateCode: { fa: "تولید کد...", en: "Generate code..." },
  copyCode: { fa: "📋 کپی کد", en: "📋 Copy Code" },
  copiedCode: { fa: "✓ کپی شد!", en: "✓ Copied!" },
  createRoomAction: { fa: "🎮 ایجاد اتاق", en: "🎮 Create Room" },
  joinRoomAction: { fa: "✅ پیوستن به اتاق", en: "✅ Join Room" },
  enterRoomCode: { fa: "کد اتاق را وارد کنید...", en: "Enter room code..." },
  loggedInLabel: { fa: "وارد شده", en: "logged in" },
  findMatchTitle: { fa: "🌐 یافتن حریف", en: "🌐 Find Match" },
  searchingAs: { fa: "در حال جستجو با نام", en: "Searching as" },
  matchmakingStarts: { fa: "تطبیق به‌صورت خودکار شروع می‌شود…", en: "Matchmaking starts automatically…" },
  playersSelected: { fa: "بازیکنان انتخاب‌شده", en: "Players Selected" },
  searchingLabel: { fa: "در حال جستجو...", en: "Searching..." },
  playersWaiting: { fa: "بازیکنان منتظر", en: "Players Waiting" },
  cancelSearch: { fa: "✕ لغو جستجو", en: "✕ Cancel Search" },
  waitingForMorePlayers: { fa: "در انتظار", en: "Waiting for" },
  morePlayerSuffix: { fa: "بازیکن دیگر", en: "more player(s)" },
  roomPrefix: { fa: "اتاق", en: "Room" },
  guest: { fa: "مهمان", en: "Guest" },
  you: { fa: "شما", en: "You" },
  disableMicrophoneShort: { fa: "خاموش کردن میکروفون", en: "Disable microphone" },
  enableMicrophoneShort: { fa: "روشن کردن میکروفون", en: "Enable microphone" },
  turnTimeLeft: { fa: "زمان باقی‌مانده", en: "Time left" },
  secondsShort: { fa: "ثانیه", en: "s" },
  turnSkipped: { fa: "رد شد", en: "was skipped" },
  merchantGirl: { fa: "تاجر دختر را می‌خواهید", en: "Choose merchant girl" },
  itsTurn: { fa: "نوبت", en: "It's" },
  rematchRequestTitle: { fa: "درخواست بازی دوباره", en: "Rematch Request" },
  rematchRequestMessage: { fa: "دوست شما می‌خواهد دوباره بازی کند.", en: "Your friend wants to play again." },
  accept: { fa: "قبول", en: "Accept" },
  decline: { fa: "رد", en: "Decline" },
  waitingRematchVotes: { fa: "در انتظار پاسخ بازیکنان دیگر...", en: "Waiting for other players to respond..." },
  loginFirst: { fa: "لطفاً ابتدا وارد شوید", en: "Please login first" },
  enterRoomCodeAlert: { fa: "لطفاً کد اتاق را وارد کنید", en: "Please enter room code" },
  onlyHostStart: { fa: "فقط میزبان می‌تواند بازی را شروع کند", en: "Only the room host can start the game" },
  needAtLeastTwo: { fa: "حداقل ۲ بازیکن برای شروع لازم است", en: "Need at least 2 players to start" },
  rewardsAdded: { fa: "🎉 پاداش‌ها به حساب شما اضافه شد", en: "🎉 Rewards added to your account" },
  profile: { fa: "پروفایل", en: "Profile" },
  accountManagement: { fa: "مدیریت حساب", en: "Account Management" },
  logout: { fa: "خروج از حساب", en: "Log Out" },
  accountQuickActions: { fa: "دسترسی سریع به حساب", en: "Quick access to your account" },
  accountCenterTitle: { fa: "پروفایل", en: "Profile" },
  accountCenterDesc: { fa: "پروفایل", en: "Profile" },
  noEmailSaved: { fa: "ایمیلی ذخیره نشده است", en: "No email saved" },
  userCode: { fa: "کد کاربر", en: "User Code" },
  gemsLabel: { fa: "الماس", en: "Diamonds" },
  usernameLabel: { fa: "نام کاربری", en: "Username" },
  emailLabel: { fa: "ایمیل", en: "Email" },
  memberSince: { fa: "عضویت از", en: "Member Since" },
  sessionActions: { fa: "عملیات حساب", en: "Session Actions" },
  backToMenu: { fa: "بازگشت به منو", en: "Back to Menu" },
  shopPage: { fa: "فروشگاه", en: "Shop" },
  friendsPage: { fa: "دوستان", en: "Friends" },
  mainPage: { fa: "خانه", en: "Home" },
  groupsPage: { fa: "گروه‌ها", en: "Groups" },
  eventsPage: { fa: "رویدادها", en: "Events" },
  shopTitle: { fa: "فروشگاه", en: "Shop" },
  shopDesc: { fa: "فروشگاه", en: "Shop" },
  off: { fa: "تخفیف", en: "OFF" },
  watchAd: { fa: "تماشای تبلیغ", en: "Watch Ad" },
  coinsBannerTitle: { fa: "بسته‌های سکه", en: "Coin Packs" },
  coinsBannerDesc: { fa: "برای خرید سریع کارت‌ها سکه بگیرید.", en: "Grab coins for faster card purchases." },
  diamondsBannerTitle: { fa: "بسته‌های الماس", en: "Diamond Packs" },
  diamondsBannerDesc: { fa: "الماس بیشتری برای پیشرفت و خرید ویژه.", en: "Get more diamonds for progression and special buys." },
  stickersBannerTitle: { fa: "بسته‌های استیکر", en: "Sticker Packs" },
  stickersBannerDesc: { fa: "استیکرهای جدید برای گفتگو و بازی.", en: "Collect stickers for chat and play." },
  avatarsBannerTitle: { fa: "بسته‌های آواتار", en: "Avatar Packs" },
  avatarsBannerDesc: { fa: "آواتارهای جدید برای پروفایل شما.", en: "Unlock new avatars for your profile." },
  avatarName1: { fa: "تاجر اصیل", en: "The Merchant" },
  avatarName2: { fa: "دختر تاجر", en: "Merchant Girl" },
  avatarName3: { fa: "تاجر کویر", en: "Desert Merchant" },
  avatarName4: { fa: "فروشنده جواهر", en: "Gem Seller" },
  avatarName5: { fa: "تاجر ارشد ", en: "Master Merchant" },
  avatarName6: { fa: "بانوی بازار", en: "Market Lady" },
  aboutUs: { fa: "درباره ما", en: "About Us" },
  aboutUsTitle: { fa: "درباره ما", en: "About Us" },
  aboutUsBody1: {
    fa: "Gemstone Guilds یک تجربه دیجیتال الهام‌گرفته از دنیای Splendor است که برای بازی محلی، آنلاین و رقابتی طراحی شده است.",
    en: "Gemstone Guilds is a digital experience inspired by Splendor, designed for local, online, and competitive play.",
  },
  aboutUsBody2: {
    fa: "هدف ما ساختن یک بازی زیبا، روان و اجتماعی است تا بازیکنان بتوانند با دوستانشان رقابت کنند، پیشرفت کنند و از فضای بازی لذت ببرند.",
    en: "Our goal is to build a beautiful, smooth, social game where players can compete with friends, progress, and enjoy the atmosphere.",
  },
  aboutUsBody3: {
    fa: "از پشتیبانی و بازخورد شما ممنونیم. هر پیشنهاد شما به بهتر شدن بازی کمک می‌کند.",
    en: "Thank you for your support and feedback. Every suggestion helps improve the game.",
  },
  logoutConfirmTitle: {
    fa: "آیا مطمئن هستید که می‌خواهید از حساب خود خارج شوید؟",
    en: "Are you sure you want to log out of your account?",
  },
    // Tutorial page
  tutorialSubtitle: {
    fa: "راه‌های مختلف یادگیری قوانین و استراتژی‌های بازی",
    en: "Different ways to learn the rules and strategies",
  },
  // ...

  logoutConfirmStay: { fa: "ماندن", en: "Stay" },
  logoutConfirmApprove: { fa: "خروج از حساب", en: "Log Out the Account" },
  loginTitle: { fa: "ورود", en: "Login" },
  signupTitle: { fa: "ثبت نام", en: "Sign Up" },
  passwordLabel: { fa: "رمز عبور", en: "Password" },
  enterUsername: { fa: "نام کاربری را وارد کنید...", en: "Enter username..." },
  enterPassword: { fa: "رمز عبور را وارد کنید...", en: "Enter password..." },
  chooseUsername: { fa: "یک نام کاربری انتخاب کنید...", en: "Choose a username..." },
  optionalEmail: { fa: "ایمیل (اختیاری)", en: "Email (optional)" },
  enterEmail: { fa: "ایمیل...", en: "Email..." },
  createPassword: { fa: "یک رمز عبور بسازید...", en: "Create a password..." },
  invalidCredentials: { fa: "نام کاربری یا رمز عبور نادرست است", en: "Invalid username or password" },
  usernameExists: { fa: "این نام کاربری قبلا ثبت شده است", en: "Username already exists (or invalid data)." },
  createAccount: { fa: "ساخت حساب", en: "Create account" },
  alreadyHaveAccountPrompt: { fa: "قبلا حساب ساخته‌اید؟", en: "Already have an account?" },
  alreadyHaveAccount: { fa: "قبلا حساب ساخته‌اید؟ وارد شوید", en: "Already have an account? Login" },
  backLabel: { fa: "بازگشت", en: "Back" },
  editProfile: { fa: "ویرایش پروفایل", en: "Edit Profile" },
  saveChanges: { fa: "ذخیره تغییرات", en: "Save Changes" },
  profileUpdated: { fa: "پروفایل با موفقیت بروزرسانی شد", en: "Profile updated successfully" },
  profileUpdateFailed: { fa: "بروزرسانی پروفایل انجام نشد", en: "Could not update profile" },
  scoresLabel: { fa: "امتیاز", en: "Score" },
  rankGroups: { fa: "رتبه‌بندی گروه‌ها", en: "Rank Groups" },
  groupInfo: { fa: "اطلاعات گروه", en: "Group Info" },
  closeLabel: { fa: "بستن", en: "Close" },
  leaveGroup: { fa: "ترک گروه", en: "Leave Group" },
  groupLeftPrevious: { fa: "ابتدا از گروه قبلی خارج شدید", en: "You left your previous group first." },
  groupChat: { fa: "چت گروه", en: "Group Chat" },
  yourGroup: { fa: "گروه شما", en: "Your Group" },
  groupCode: { fa: "کد گروه", en: "Group Code" },
  noGroupJoined: { fa: "هنوز در هیچ گروهی نیستید. یک گروه بسازید یا به یکی ملحق شوید.", en: "You are not in a group yet. Create one or join one." },
  singleGroupNotice: { fa: "هر بازیکن فقط می‌تواند در یک گروه باشد. برای ساختن یا پیوستن به گروه جدید، ابتدا از گروه قبلی خارج می‌شوید.", en: "Each player can only stay in one group. Creating or joining another group leaves the previous one first." },
  flagLabel: { fa: "پرچم گروه", en: "Group Flag" },
  coinsOffer1: { fa: "تبلیغ روزانه سکه", en: "Daily Coin Ad" },
  coinsOffer2: { fa: "کیف سکه کوچک", en: "Small Coin Wallet" },
  coinsOffer3: { fa: "کیف سکه نقره‌ای", en: "Silver Coin Wallet" },
  coinsOffer4: { fa: "صندوق سکه طلایی", en: "Gold Coin Chest" },
  coinsOffer5: { fa: "گنجینه سکه سلطنتی", en: "Royal Coin Vault" },
  coinsOffer6: { fa: "انبار بزرگ سکه", en: "Grand Coin Reserve" },
  diamondsOffer1: { fa: "تبلیغ روزانه الماس", en: "Daily Diamond Ad" },
  diamondsOffer2: { fa: "بسته الماس کوچک", en: "Small Diamond Pack" },
  diamondsOffer3: { fa: "جعبه الماس نقره‌ای", en: "Silver Diamond Box" },
  diamondsOffer4: { fa: "صندوق الماس طلایی", en: "Gold Diamond Chest" },
  diamondsOffer5: { fa: "گنجینه الماس سلطنتی", en: "Royal Diamond Vault" },
  diamondsOffer6: { fa: "ذخیره بزرگ الماس", en: "Grand Diamond Reserve" },
  stickersOffer1: { fa: "تبلیغ استیکر روز", en: "Daily Sticker Ad" },
  stickersOffer2: { fa: "استیکر خنده", en: "Laugh Sticker" },
  stickersOffer3: { fa: "استیکر برد", en: "Victory Sticker" },
  stickersOffer4: { fa: "استیکر قلب", en: "Heart Sticker" },
  stickersOffer5: { fa: "استیکر تاج", en: "Crown Sticker" },
  stickersOffer6: { fa: "استیکر قهرمان", en: "Champion Sticker" },
  avatarsOffer1: { fa: "تبلیغ آواتار روز", en: "Daily Avatar Ad" },
  avatarsOffer2: { fa: "آواتار برنز", en: "Bronze Avatar" },
  avatarsOffer3: { fa: "آواتار نقره", en: "Silver Avatar" },
  avatarsOffer4: { fa: "آواتار طلا", en: "Gold Avatar" },
  avatarsOffer5: { fa: "آواتار الماس", en: "Diamond Avatar" },
  avatarsOffer6: { fa: "آواتار سلطنتی", en: "Royal Avatar" },
  coin_pack_small: { fa: "بسته کوچک سکه", en: "Small Coin Pack" },
  coin_pack_large: { fa: "بسته بزرگ سکه", en: "Large Coin Pack" },
  gem_pack_small: { fa: "بسته کوچک الماس", en: "Small Diamond Pack" },
  gem_pack_large: { fa: "بسته بزرگ الماس", en: "Large Diamond Pack" },
  avatar_pack: { fa: "بسته آواتار", en: "Avatar Pack" },
  sticker_pack: { fa: "بسته استیکر", en: "Sticker Pack" },
  amountLabel: { fa: "مقدار", en: "Amount" },
  buyNow: { fa: "خرید", en: "Buy Now" },
  wallet: { fa: "کیف آیتم‌ها", en: "Wallet" },
  avatarsLabel: { fa: "آواتارها", en: "Avatars" },
  stickersLabel: { fa: "استیکرها", en: "Stickers" },
  dailyReward: { fa: "جایزه روزانه", en: "Daily Reward" },
  dailyRewardDesc: { fa: "هفت جایزه متفاوت برای روزهای هفته وجود دارد.", en: "There are seven different rewards for the days of the week." },
  claimReward: { fa: "دریافت جایزه", en: "Claim Reward" },
  dailyRewardClaimed: { fa: "جایزه امروز قبلاً دریافت شده است.", en: "Today's reward has already been claimed." },
  dailyRewardSuccess: { fa: "جایزه روزانه با موفقیت اضافه شد.", en: "Daily reward added successfully." },
  purchaseSuccess: { fa: "خرید با موفقیت انجام شد.", en: "Purchase completed successfully." },
  weeklyRewards: { fa: "جوایز هفتگی", en: "Weekly Rewards" },
  dayLabel: { fa: "روز", en: "Day" },
  avatarReward: { fa: "۱ آواتار", en: "1 avatar" },
  stickerReward: { fa: "۱ استیکر", en: "1 sticker" },
  claimed: { fa: "دریافت شد", en: "Claimed" },
  rewardResetRule: { fa: "اگر یک روز را از دست بدهید، روند جایزه از روز اول شروع می‌شود.", en: "If you miss a day, the reward streak restarts from day 1." },
  friendsTitle: { fa: "دوستان", en: "Friends" },
  friendsDesc: { fa: "دوستان", en: "Friends" },
  yourUserCode: { fa: "کد اختصاصی شما", en: "Your unique user code" },
  searchUsersPlaceholder: { fa: "جستجو با نام کاربری یا کد کاربر", en: "Search by username or user code" },
  noPlayersFound: { fa: "بازیکنی پیدا نشد", en: "No players found" },
  sendRequest: { fa: "ارسال درخواست", en: "Send Request" },
  requestSentTitle: { fa: "درخواست ارسال شد", en: "Request Sent" },
  requestSentMessage: { fa: "درخواست دوستی شما با موفقیت ارسال شد.", en: "Your friend request was sent successfully." },
  requestAlreadySentTitle: { fa: "درخواست قبلاً ارسال شده", en: "Request Already Sent" },
  requestAlreadySentMessage: { fa: "شما قبلاً برای این بازیکن درخواست دوستی فرستاده‌اید.", en: "You've already sent a request to this player." },
  alreadyFriendsTitle: { fa: "قبلاً دوست هستید", en: "Already Friends" },
  alreadyFriendsMessage: { fa: "شما قبلاً با این بازیکن دوست هستید.", en: "You are already friends with this player." },
  chatsTab: { fa: "چت‌ها", en: "Chats" },
  friendsTab: { fa: "دوستان", en: "Friends" },
  requestsTab: { fa: "درخواست‌ها", en: "Requests" },
  noChatsYet: { fa: "هنوز چتی ندارید", en: "No chats yet" },
  selectChatPrompt: { fa: "برای شروع گفت‌وگو یکی از دوستان خود را انتخاب کنید.", en: "Choose one of your friends to start chatting." },
  openChatFromFriends: { fa: "برای شروع چت از بخش دوستان روی «باز کردن چت» بزنید.", en: "Open a friend from the Friends tab to start chatting." },
  noFriendsYet: { fa: "هنوز دوستی اضافه نشده است", en: "No friends added yet" },
  openChat: { fa: "باز کردن چت", en: "Open Chat" },
  sendGameInvite: { fa: "دعوت به بازی", en: "Send Game Invite" },
  incomingGameInvite: { fa: "دوست شما شما را به بازی دعوت کرده است.", en: "Your friend invited you to play." },
  playWithFriend: { fa: "بازی با دوست", en: "Play With Friend" },
  noRequestsYet: { fa: "درخواستی وجود ندارد", en: "No requests yet" },
  groupsTitle: { fa: "گروه‌ها", en: "Groups" },
  groupsDesc: { fa: "گروه بسازید یا گروه‌های موجود را پیدا کنید و درخواست عضویت بدهید.", en: "Create groups or find existing groups and request to join." },
  createGroupTab: { fa: "ساخت گروه", en: "Create Group" },
  findGroupTab: { fa: "یافتن گروه", en: "Find Group" },
  groupName: { fa: "نام گروه", en: "Group Name" },
  minimumEntryScore: { fa: "حداقل امتیاز ورود", en: "Minimum Entry Score" },
  descriptionLabel: { fa: "توضیحات", en: "Description" },
  groupStatus: { fa: "وضعیت گروه", en: "Group Status" },
  publicGroup: { fa: "عمومی", en: "Public" },
  privateGroup: { fa: "خصوصی", en: "Private" },
  closedGroup: { fa: "بسته", en: "Closed" },
  createGroupCost: { fa: "ساخت گروه با 100 جم", en: "Create Group for 100 Gems" },
  notEnoughGems: { fa: "جم کافی ندارید", en: "You do not have enough gems" },
  groupCreatedSuccess: { fa: "گروه با موفقیت ساخته شد", en: "Group created successfully" },
  groupSyncError: {
    fa: "اتصال به سرور گروه‌ها برقرار نشد. یک بار سرور را ری‌استارت کنید و دوباره تلاش کنید.",
    en: "Could not reach the groups server. Restart the server once and try again.",
  },
  searchGroups: { fa: "جستجوی گروه با نام یا کد", en: "Search groups by name or code" },
  allMembers: { fa: "همه اعضا", en: "All member counts" },
  smallGroups: { fa: "گروه‌های کوچک", en: "Small groups" },
  largeGroups: { fa: "گروه‌های بزرگ", en: "Large groups" },
  allStatuses: { fa: "همه وضعیت‌ها", en: "All statuses" },
  noGroupsFound: { fa: "گروهی پیدا نشد", en: "No groups found" },
  noDescription: { fa: "توضیحی ثبت نشده است", en: "No description provided" },
  joinRequestSent: { fa: "درخواست عضویت ارسال شد", en: "Join request sent" },
  joinRequestSentMessage: { fa: "درخواست عضویت شما با موفقیت ارسال شد.", en: "Your join request was sent successfully." },
  joinRequestAlreadySent: { fa: "درخواست قبلاً ارسال شده است", en: "Join request was already sent" },
  requestJoin: { fa: "درخواست عضویت", en: "Request to Join" },
  joinGroup: { fa: "پیوستن به گروه", en: "Join Group" },
  groupJoinedSuccess: { fa: "با موفقیت به گروه پیوستید", en: "You joined the group successfully." },
  groupClosedMessage: { fa: "این گروه بسته است و امکان درخواست یا عضویت ندارد.", en: "This group is closed. You cannot request or join it." },
  privateGroupRequest: { fa: "ارسال درخواست", en: "Send Request" },
  rankPlayers: { fa: "رتبه‌بندی بازیکنان", en: "Rank Players" },
  topGroups: { fa: "بهترین گروه‌ها", en: "Top Groups" },
  topPlayers: { fa: "بهترین بازیکنان", en: "Top Players" },
  groupSettings: { fa: "تنظیمات گروه", en: "Group Settings" },
  editGroupSettings: { fa: "ویرایش تنظیمات گروه", en: "Edit Group Settings" },
  saveGroupSettings: { fa: "ذخیره تنظیمات", en: "Save Settings" },
  groupUpdatedSuccess: { fa: "تنظیمات گروه با موفقیت ذخیره شد", en: "Group settings saved successfully." },
  groupRequestFor: { fa: "درخواست عضویت برای گروه", en: "Group join request for" },
  minPlayersLabel: { fa: "حداقل بازیکن", en: "Min Players" },
  maxPlayersLabel: { fa: "حداکثر بازیکن", en: "Max Players" },
  groupActionBlockedTitle: { fa: "ابتدا از گروه فعلی خارج شوید", en: "Leave your current group first" },
  groupActionBlockedMessage: { fa: "تا وقتی در یک گروه هستید نمی‌توانید گروه جدید بسازید یا درخواست عضویت جدید بفرستید.", en: "You cannot create a new group or send another join request while you are already in a group." },
  leaveGroupConfirmTitle: { fa: "آیا مطمئن هستید که می‌خواهید از گروه خارج شوید؟", en: "Are you sure you want to leave the group?" },
  removeMember: { fa: "حذف عضو", en: "Remove Member" },
  removeMemberConfirmTitle: { fa: "این عضو از گروه حذف شود؟", en: "Remove this member from the group?" },
  removeMemberConfirmMessage: { fa: "این بازیکن فوراً از گروه حذف می‌شود.", en: "This player will be removed from the group immediately." },
  creatorLabel: { fa: "سازنده", en: "Creator" },
  eventsTitle: { fa: "لیگ‌ها و رویدادها", en: "Leagues & Events" },
  eventsDesc: { fa: "در رقابت‌های مختلف شرکت کنید و جوایز بیشتری به دست آورید.", en: "Compete in leagues and special events for bigger rewards." },
  leaguesTitle: { fa: "لیگ‌ها", en: "Leagues" },
  liveEventsTitle: { fa: "رویدادهای فعال", en: "Live Events" },
  bronzeLeague: { fa: "لیگ برنز", en: "Bronze League" },
  bronzeLeagueDesc: { fa: "رقابت برای بازیکنان تازه‌کار با پاداش‌های هفتگی.", en: "Starter competition with weekly rewards." },
  silverLeague: { fa: "لیگ نقره", en: "Silver League" },
  silverLeagueDesc: { fa: "رقابت متعادل برای بازیکنان فعال‌تر.", en: "Balanced competition for active players." },
  diamondLeague: { fa: "لیگ الماس", en: "Diamond League" },
  diamondLeagueDesc: { fa: "رقابت سطح بالا با بهترین پاداش‌ها.", en: "High-tier competition with premium rewards." },
  weekendCup: { fa: "جام آخر هفته", en: "Weekend Cup" },
  weekendCupDesc: { fa: "در آخر هفته بازی کنید و امتیاز ویژه بگیرید.", en: "Play during the weekend for bonus rewards." },
  speedEvent: { fa: "رویداد سرعت", en: "Speed Event" },
  speedEventDesc: { fa: "بازی‌های سریع با زمان کمتر برای هر نوبت.", en: "Fast-paced matches with shorter turn timers." },
  guildClash: { fa: "نبرد گیلدها", en: "Guild Clash" },
  guildClashDesc: { fa: "اعضای گروه‌ها برای صدر جدول رقابت می‌کنند.", en: "Groups compete for the top of the leaderboard." },
  paymentGatewayTitle: { fa: "درگاه پرداخت", en: "Payment Gateway" },
  paymentGatewayDesc: { fa: "پس از تایید پرداخت، خرید به کیف شما اضافه می‌شود.", en: "After confirming payment, the purchase is added to your wallet." },
  paymentAmount: { fa: "مبلغ پرداخت", en: "Payment Amount" },
  confirmPayment: { fa: "تایید پرداخت", en: "Confirm Payment" },
  invalidPayment: { fa: "پرداخت نامعتبر است", en: "Invalid payment request" },
  deadMansDrawAdvancedRings: { fa: "حلقه‌های پیشرفته", en: "Advanced Rings" },
  deadMansDrawAdvancedPowers: { fa: "قدرت‌های پیشرفته", en: "Advanced Powers" },
  deadMansDrawChoosePower: { fa: "{{player}}، یک قدرت انتخاب کن", en: "{{player}}, choose 1 power" },
  deadMansDrawChoosePowerBody: { fa: "بازیکن {{player}} دو قدرت رو را می‌بیند، یکی را برای کل بازی نگه می‌دارد و دیگری را کنار می‌گذارد.", en: "Player {{player}} reviews 2 face-up powers, keeps 1 for the full game, and discards the other." },
  deadMansDrawImReady: { fa: "آماده‌ام", en: "I'm ready" },
  deadMansDrawPlayerName: { fa: "بازیکن {{number}}", en: "Player {{number}}" },
  deadMansDrawRivalAI: { fa: "ربات رقیب {{number}}", en: "Rival AI {{number}}" },
  deadMansDrawCurrentExplorer: { fa: "کاوشگر فعلی", en: "Current explorer" },
  deadMansDrawBackToMenu: { fa: "بازگشت به منو", en: "Back to menu" },
  deadMansDrawForcedReveals: { fa: "کارت‌های اجباری باقی‌مانده: {{count}}", en: "Forced reveals left: {{count}}" },
  deadMansDrawBotThinking: { fa: "ربات در حال فکر کردن به حرکت بعدی است...", en: "The bot is thinking through its move..." },
  deadMansDrawWaitingTurn: { fa: "باید صبر کنی تا نوبت فعال تمام شود و بتوانی بازی کنی.", en: "Waiting for the active turn to finish before you can play." },
  deadMansDrawDrawDeck: { fa: "دستهٔ کشیدن", en: "Draw deck" },
  deadMansDrawBurnPile: { fa: "پشتهٔ سوخته", en: "Burn pile" },
  deadMansDrawReveal: { fa: "رو کردن کارت", en: "Reveal Card" },
  deadMansDrawCollect: { fa: "جمع کردن گنج", en: "Collect Treasure" },
  deadMansDrawTreasureArea: { fa: "ناحیهٔ گنج", en: "Treasure area" },
  deadMansDrawRevealedCount: { fa: "{{count}} کارت رو شده", en: "{{count}} revealed" },
  deadMansDrawRevealHint: { fa: "برای ساختن ردیف گنج، کارت‌ها را رو کن.", en: "Reveal cards to build a treasure run." },
  deadMansDrawResolveEffect: { fa: "حل اثر کارت", en: "Resolve effect" },
  deadMansDrawActiveChoices: { fa: "انتخاب‌های کارت فعال", en: "Active card choices" },
  deadMansDrawNoChoices: { fa: "اثرهایی که نیاز به انتخاب داشته باشند اینجا ظاهر می‌شوند.", en: "Card effects that need a choice will appear here." },
  deadMansDrawPassDevicePrefix: { fa: "دستگاه را به", en: "Pass the device to" },
  deadMansDrawPassDeviceSuffix: { fa: "بده و بعد دکمهٔ", en: "then press" },
  deadMansDrawReady: { fa: "آماده", en: "ready" },
  deadMansDrawPeekedCards: { fa: "کارت‌های دیده‌شده", en: "Peeked cards" },
  deadMansDrawFirstCard: { fa: "اول", en: "First" },
  deadMansDrawSecondCard: { fa: "دوم", en: "Second" },
  deadMansDrawThirdCard: { fa: "سوم", en: "Third" },
  deadMansDrawRevealTopCard: { fa: "رو کردن کارت بالا", en: "Reveal top card" },
  deadMansDrawCollectNow: { fa: "الان جمع کن", en: "Collect now" },
  deadMansDrawTargetPlayer: { fa: "بازیکن هدف {{player}}", en: "Target player {{player}}" },
  deadMansDrawChooseStashCard: { fa: "یک کارت از انبار خودت انتخاب کن", en: "Choose a card from your stash" },
  deadMansDrawChooseBurnedCard: { fa: "یک کارت سوخته برای بازی دوباره انتخاب کن", en: "Choose a burnt card to replay" },
  deadMansDrawExplorerLabel: { fa: "کاوشگر {{number}}", en: "Explorer {{number}}" },
  deadMansDrawCardCount: { fa: "{{count}} کارت", en: "{{count}} cards" },
  deadMansDrawStackTopValue: { fa: "بالاترین امتیاز: {{value}}", en: "Top value: {{value}}" },
  deadMansDrawStackBehindValues: { fa: "پشت آن: {{values}}", en: "Behind it: {{values}}" },
  deadMansDrawBonusPreviewTitle: { fa: "{{player}} گنج جایزه را برداشت", en: "{{player}} recovered bonus treasure" },
  deadMansDrawBonusPreviewBody: { fa: "این کارت‌ها از پشتهٔ سوخته آمده‌اند. وقتی همه آن‌ها را دیدند، تایید کن تا بازیکن بعدی شروع کند.", en: "These cards came from the burn pile. Click yes when everyone has reviewed them and the next player can begin." },
  deadMansDrawBonusPreviewConfirm: { fa: "بله، بازیکن بعدی", en: "Yes, next player" },
  deadMansDrawGameOver: { fa: "پایان بازی", en: "Game Over" },
  deadMansDrawWinnerLine: { fa: "{{winners}} برنده شد", en: "{{winners}} win" },
  deadMansDrawGameOverBody: { fa: "امتیاز نهایی با بالاترین کارت هر ستون حساب می‌شود. در تساوی، بازیکنی که کارت بیشتری دارد برنده است.", en: "Final scoring counts the highest visible card from each suit stack. If scores tie, the player with more cards wins." },
  deadMansDrawTiebreakBody: { fa: "امتیازها روی {{score}} مساوی شد. {{winners}} به خاطر داشتن کارت‌های بیشتر برنده شد: {{cards}}.", en: "They were tied on points at {{score}}. {{winners}} win because they have more cards: {{cards}}." },
  deadMansDrawScoreLine: { fa: "امتیاز {{score}} · کارت {{cards}}", en: "Score {{score}} · Cards {{cards}}" },
  deadMansDrawPlayAgain: { fa: "بازی دوباره", en: "Play again" },
  deadMansDrawSpecialPowersLabel: { fa: "قدرت‌های ویژه", en: "Special Powers" },
  deadMansDrawSpecialPowersTitle: { fa: "فهرست قدرت‌های ویژه", en: "Special power roster" },
  deadMansDrawSpecialPowersSubtitle: { fa: "قدرت‌های ویژهٔ ددمنز دراو طبق فهرستی که دادی اینجا جمع شده‌اند.", en: "The Dead Man's Draw special powers you provided are listed here for quick reference." },
  deadMansDrawSuitAstrolabe: { fa: "ستاره‌یاب", en: "Astrolabe" },
  deadMansDrawSuitPistol: { fa: "توپ", en: "Pistol" },
  deadMansDrawSuitDagger: { fa: "شمشیر", en: "Dagger" },
  deadMansDrawSuitCarpet: { fa: "لنگر", en: "Carpet" },
  deadMansDrawSuitSnake: { fa: "کراکن", en: "Snake" },
  deadMansDrawSuitCoin: { fa: "سکه", en: "Coin" },
  deadMansDrawSuitHorseshoe: { fa: "قلاب", en: "Horseshoe" },
  deadMansDrawSuitMap: { fa: "نقشه", en: "Map" },
  deadMansDrawSuitChest: { fa: "صندوق", en: "Chest" },
  deadMansDrawSuitKey: { fa: "کلید", en: "Key" },
  deadMansDrawSuitHelpAstrolabe: { fa: "ستاره‌یاب کارت‌های بالای دسته را نشان می‌دهد و بعد می‌توانی تصمیم بگیری رو کنی یا همان حالا جمع کنی.", en: "Astrolabe shows the top upcoming cards, then lets you decide whether to reveal or collect." },
  deadMansDrawSuitHelpPistol: { fa: "توپ به تو اجازه می‌دهد کارت بالایی یکی از ستون‌های حریف را بسوزانی؛ با Gunnie حتی کل ستون می‌سوزد.", en: "Pistol lets you burn the top card from an opponent's stack; with Gunnie it can blast the whole stack." },
  deadMansDrawSuitHelpDagger: { fa: "شمشیر کارت بالایی یکی از ستون‌های حریف را می‌دزدد و وارد ناحیهٔ گنج تو می‌کند.", en: "Dagger steals the top card from an opponent's stack into your treasure area." },
  deadMansDrawSuitHelpCarpet: { fa: "لنگر اگر بترکی، بخشی از گنج را نجات می‌دهد؛ Ghallegar حتی خودش و کارت بعدی را هم حفظ می‌کند.", en: "Carpet can save part of your treasure on a bust; Ghallegar can also protect it and the next card." },
  deadMansDrawSuitHelpSnake: { fa: "کراکن تو را مجبور به رو کردن کارت‌های بیشتری می‌کند و ریسک ترکیدن را بالا می‌برد.", en: "Kraken forces extra reveals and raises your bust risk." },
  deadMansDrawSuitHelpCoin: { fa: "سکه فقط امتیاز خالص است و اگر Sir Lovesword داشته باشی، از روی دسته مستقیم بانک می‌شود.", en: "Coin is pure score, and Sir Lovesword banks it immediately when revealed from the draw deck." },
  deadMansDrawSuitHelpHorseshoe: { fa: "قلاب کارت بالایی یکی از ستون‌های خودت را دوباره وارد ناحیهٔ گنج می‌کند.", en: "Hook plays the top card from one of your own stacks back into the treasure area." },
  deadMansDrawSuitHelpMap: { fa: "نقشه یک کارت از پشتهٔ سوخته را برمی‌گرداند تا دوباره وارد ناحیهٔ گنج شود.", en: "Map recovers a card from the burn pile and plays it back into the treasure area." },
  deadMansDrawSuitHelpChest: { fa: "اگر در همان نوبت کلید هم داشته باشی، بعد از جمع کردن به اندازهٔ تعداد کارت‌های این نوبت جایزه می‌گیری.", en: "If you also have a Key in the same haul, collecting grants bonus cards equal to the size of the haul." },
  deadMansDrawSuitHelpKey: { fa: "کلید همراه با صندوق فعال می‌شود و جایزهٔ آن نوبت را باز می‌کند.", en: "Key works with Chest to unlock that turn's bonus treasure." },
  deadMansDrawTreasureHelpTitle: { fa: "کمک کارت {{suit}}", en: "{{suit}} help" },
  deadMansDrawTreasureHelpEmpty: { fa: "وقتی کارتی در ناحیهٔ گنج رو شود، توضیح آن اینجا نمایش داده می‌شود.", en: "When a card is revealed in the treasure area, its help text appears here." },
  deadMansDrawCollectBlockedSnakeAstrolabe: { fa: "وقتی کراکن روی میز است و کارت بعدی ستاره‌یاب است، هنوز نمی‌توانی گنج را جمع کنی.", en: "When Kraken is showing and the next card is Astrolabe, you still cannot collect treasure." },
  deadMansDrawActionChooseMode: { fa: "هر بازیکن یکی از دو قدرت حلقهٔ رو را انتخاب می‌کند.", en: "Each player chooses 1 of 2 face-up ring powers." },
  deadMansDrawActionRevealOrCollect: { fa: "بین رو کردن کارت و جمع کردن گنج یکی را انتخاب کن.", en: "Choose whether to reveal or collect." },
  deadMansDrawActionTurnBegins: { fa: "نوبت بازیکن {{player}} شروع شد.", en: "Player {{player}}'s turn begins." },
  deadMansDrawActionBustTurnBegins: { fa: "بعد از ترکیدن نوبت به بازیکن {{player}} رسید.", en: "Player {{player}} takes over after the bust." },
  deadMansDrawActionCarpetSaved: { fa: "ترکیدی! لنگر بخشی از گنج را نجات داد.", en: "Bust! The Carpet saved part of the treasure." },
  deadMansDrawActionFullBust: { fa: "ترکیدی! همه‌چیز به پشتهٔ سوخته رفت.", en: "Bust! Everything goes to the burn pile." },
  deadMansDrawActionSnakeBurned: { fa: "کراکن رو شد، اما به خاطر قدرتت مستقیم به پشتهٔ سوخته رفت.", en: "A snake just revealed, but because of your power it went to the burn pile." },
  deadMansDrawActionSnakeForced: { fa: "کراکن رو شد: باید ۲ کارت دیگر هم رو کنی.", en: "Snake revealed: 2 more cards must be played." },
  deadMansDrawActionAstrolabeEmpty: { fa: "ستاره‌یاب چیزی برای دیدن پیدا نکرد.", en: "Astrolabe found nothing to inspect." },
  deadMansDrawActionAstrolabeInspect: { fa: "ستاره‌یاب: کارت(های) بالایی را ببین، بعد رو کن یا جمع کن.", en: "Astrolabe: inspect the top card(s), then reveal or collect." },
  deadMansDrawActionPistolNoTarget: { fa: "توپ هیچ هدفی پیدا نکرد.", en: "Pistol found no target." },
  deadMansDrawActionPistolChoose: { fa: "توپ: یک کارت از بازیکن دیگر را برای سوزاندن انتخاب کن.", en: "Pistol: choose a card to burn from another player." },
  deadMansDrawActionDaggerNoTarget: { fa: "شمشیر هیچ هدف قانونی پیدا نکرد.", en: "Dagger found no legal target." },
  deadMansDrawActionDaggerChoose: { fa: "شمشیر: یک کارت را به ناحیهٔ گنج بدزد.", en: "Dagger: steal a card into the treasure area." },
  deadMansDrawActionHorseshoeEmpty: { fa: "قلاب بی‌اثر شد چون در انبارت کارتی نیست.", en: "Horseshoe fizzled because there are no cards in your stash." },
  deadMansDrawActionHorseshoeChoose: { fa: "قلاب: یک کارت از انبار خودت بازی کن.", en: "Horseshoe: play a card from your own stash." },
  deadMansDrawActionMapEmpty: { fa: "نقشه هیچ گنج سوخته‌ای برای برگرداندن پیدا نکرد.", en: "Map found no burned treasure to recover." },
  deadMansDrawActionMapReaderChoose: { fa: "نقشه‌خوان: هر کارتی را از پشتهٔ سوخته انتخاب کن.", en: "Map Reader: choose any card from the burn pile." },
  deadMansDrawActionMapChoose: { fa: "نقشه: یکی از ۳ کارت سوخته را برای بازی انتخاب کن.", en: "Map: choose 1 of 3 burned cards to play." },
  deadMansDrawActionSuitAdded: { fa: "{{suit}} به ناحیهٔ گنج اضافه شد.", en: "{{suit}} added to the treasure area." },
  deadMansDrawActionCollectedBonus: { fa: "گنج را جمع کردی و {{count}} کارت جایزه هم برداشتی.", en: "Collected treasure and recovered {{count}} bonus card(s)." },
  deadMansDrawActionCollected: { fa: "گنج رو شده جمع شد.", en: "Collected the revealed treasure." },
  deadMansDrawActionAstrolabeCollect: { fa: "ستاره‌یاب نوبت را با یک جمع امن تمام کرد.", en: "Astrolabe ended the turn with a safe collect." },
  deadMansDrawActionAstrolabeReveal: { fa: "ستاره‌یاب تصمیم گرفت کارت بالایی رو شود.", en: "Astrolabe chose to reveal the top card." },
  deadMansDrawActionPistolStole: { fa: "توپ {{suit}} را به انبار خودت برد.", en: "Pistol stole {{suit}} into the Thug's stash." },
  deadMansDrawActionPistolBurned: { fa: "توپ {{suit}} را سوزاند.", en: "Pistol burned {{suit}}." },
  deadMansDrawActionDaggerStole: { fa: "شمشیر {{suit}} را دزدید.", en: "Dagger stole {{suit}}." },
  deadMansDrawActionHorseshoePlayed: { fa: "قلاب {{suit}} را از انبار بازی کرد.", en: "Horseshoe played {{suit}} from the stash." },
  deadMansDrawActionHorseshoeExtra: { fa: "قلاب فریبکار: یک کارت دیگر از انبارت انتخاب کن.", en: "Trickster Horseshoe: choose one more card from your stash." },
  deadMansDrawActionMapRecovered: { fa: "نقشه {{suit}} را برگرداند.", en: "Map recovered {{suit}}." },
  deadMansDrawActionRingLocked: { fa: "همهٔ قدرت‌های حلقه قفل شدند. بازیکن ۱ شروع می‌کند.", en: "All ring powers are locked in. Player 1 begins." },
  deadMansDrawActionChooseRing: { fa: "بازیکن {{player}}، قدرت حلقه‌ات را انتخاب کن.", en: "Player {{player}}, choose your ring power." },
  deadMansDrawPowerLeCorsaireName: { fa: "Le Corsaire — Plunder", en: "Le Corsaire — Plunder" },
  deadMansDrawPowerLeCorsaireAbility: { fa: "کارت‌های جایزه از بالای ستون‌های خالِ حریف‌ها برداشته می‌شوند.", en: "Bonus cards are taken from the top of the opponents' suit stacks." },
  deadMansDrawPowerMadamMargotName: { fa: "Madam Margot — Davy Jones's Locker", en: "Madam Margot — Davy Jones's Locker" },
  deadMansDrawPowerMadamMargotAbility: { fa: "یک حریف را انتخاب کن. هر وقت آن حریف ترکید، کارت‌هایش را بانک می‌کنی.", en: "Choose one opponent in the game. When that opponent busts, you bank their cards." },
  deadMansDrawPowerGhallegarName: { fa: "Ghallegar — Miser", en: "Ghallegar — Miser" },
  deadMansDrawPowerGhallegarAbility: { fa: "کارت قلاب و کارتی که با آن از بانک خودت بازی می‌کنی، حتی اگر بترکی جمع می‌شوند و پیش تو می‌مانند.", en: "The Hook card and the card it plays from your stash are collected and kept even if you bust." },
  deadMansDrawPowerScurvyPeteName: { fa: "Scurvy Pete — Misfire", en: "Scurvy Pete — Misfire" },
  deadMansDrawPowerScurvyPeteAbility: { fa: "وقتی حریف‌ها از توپ استفاده می‌کنند، باید یکی از کارت‌های بالای ستون‌های خودشان را هم به دورریز بفرستند.", en: "When opponents use a Cannon, they must also move one top card from one of their own suit stacks to the discard pile." },
  deadMansDrawPowerZaharaName: { fa: "Zahara — Mystic Sight", en: "Zahara — Mystic Sight" },
  deadMansDrawPowerZaharaAbility: { fa: "نماد چشم: پیش از تصمیم برای کشیدن، سه کارت بعدی را ببین.", en: "Eye symbol: Reveal three upcoming cards before deciding whether to draw." },
  deadMansDrawPowerGunnieName: { fa: "Gunnie — Master Gunner", en: "Gunnie — Master Gunner" },
  deadMansDrawPowerGunnieAbility: { fa: "نماد توپ: یک ستون کامل خال را به دورریز منتقل کن.", en: "Cannon symbol: Move an entire suit stack into the discard pile." },
  deadMansDrawPowerBlackBonnieName: { fa: "Black Bonnie — Parry", en: "Black Bonnie — Parry" },
  deadMansDrawPowerBlackBonnieAbility: { fa: "وقتی حریفی از شمشیر استفاده می‌کند، اول باید از بانک تو یک کارت کراکن بکشد.", en: "When an opponent uses a Sword, they must first draw a kraken card from your bank." },
  deadMansDrawPowerSirLoveswordName: { fa: "Sir Lovesword — Casanova", en: "Sir Lovesword — Casanova" },
  deadMansDrawPowerSirLoveswordAbility: { fa: "کارت‌های سکه وقتی از دستهٔ کشیدن رو می‌شوند، بلافاصله بانک می‌شوند.", en: "Coin cards are banked immediately when drawn from the draw pile." },
  deadMansDrawPowerSeamusQuinnName: { fa: "Seamus Quinn — Beastmaster", en: "Seamus Quinn — Beastmaster" },
  deadMansDrawPowerSeamusQuinnAbility: { fa: "نماد کراکن: حریف‌ها به‌جای دو کارت، باید چهار کارت اضافه بکشند.", en: "Kraken symbol: Opponents must draw four additional cards instead of two." },
  deadMansDrawChooseMisfireCard: { fa: "یک کارت از ستون‌های خودت برای دورریز انتخاب کن", en: "Choose one of your own top cards to discard" },
  deadMansDrawChooseTargetLabel: { fa: "انتخاب هدف", en: "Choose target" },
  deadMansDrawChooseTargetTitle: { fa: "{{player}} باید یک حریف را برای Madam Margot انتخاب کند", en: "{{player}} must choose an opponent for Madam Margot" },
  deadMansDrawChooseTargetBody: { fa: "این حریف تا آخر بازی زیر نظر Madam Margot می‌ماند. هر وقت او بترکد، کارت‌های سوخته‌اش برای تو بانک می‌شوند.", en: "That opponent stays marked for the rest of the game. Whenever they bust, their busted cards are banked for you." },
  deadMansDrawChooseTargetCta: { fa: "این بازیکن را علامت بزن", en: "Mark this player" },
  deadMansDrawPassTargetBody: { fa: "دستگاه را به بازیکن درست بده، بعد آماده را بزن تا هدف Madam Margot انتخاب شود.", en: "Pass the device to the correct player, then press ready so Madam Margot can choose a target." },
  deadMansDrawPowerPending: { fa: "هنوز قدرتش را انتخاب نکرده", en: "Power not chosen yet" },
  deadMansDrawPowerEquipped: { fa: "قدرت فعال: {{power}}", en: "Equipped power: {{power}}" },
  deadMansDrawMarkedOpponent: { fa: "· هدف: {{player}}", en: "- marked opponent: {{player}}" },
  "deadMansDrawPowerLabelle-corsaire": { fa: "Le Corsaire", en: "Le Corsaire" },
  "deadMansDrawPowerLabelmadam-margot": { fa: "Madam Margot", en: "Madam Margot" },
  deadMansDrawPowerLabelghallegar: { fa: "Ghallegar", en: "Ghallegar" },
  "deadMansDrawPowerLabelscurvy-pete": { fa: "Scurvy Pete", en: "Scurvy Pete" },
  deadMansDrawPowerLabelzahara: { fa: "Zahara", en: "Zahara" },
  deadMansDrawPowerLabelgunnie: { fa: "Gunnie", en: "Gunnie" },
  "deadMansDrawPowerLabelblack-bonnie": { fa: "Black Bonnie", en: "Black Bonnie" },
  "deadMansDrawPowerLabelsir-lovesword": { fa: "Sir Lovesword", en: "Sir Lovesword" },
  "deadMansDrawPowerLabelseamus-quinn": { fa: "Seamus Quinn", en: "Seamus Quinn" },
  deadMansDrawActionChooseMarkedOpponent: { fa: "بازیکن {{player}} باید حریفِ Madam Margot را انتخاب کند.", en: "Player {{player}} must choose which opponent Madam Margot watches." },
  deadMansDrawActionMarkedOpponent: { fa: "Madam Margot بازیکن {{player}} را علامت زد.", en: "Madam Margot marked Player {{player}}." },
  deadMansDrawActionSnakeForcedCount: { fa: "کراکن رو شد: باید {{count}} کارت دیگر هم رو کنی.", en: "Snake revealed: {{count}} more cards must be played." },
  deadMansDrawActionPlundered: { fa: "گنج را جمع کردی و {{count}} کارت جایزه از بالای ستون‌های حریف‌ها غارت شد.", en: "Collected treasure and plundered {{count}} bonus card(s) from opponents." },
  deadMansDrawActionNoPlunder: { fa: "گنج را جمع کردی، اما چیزی برای غارت در ستون‌های حریف‌ها نبود.", en: "Collected treasure, but there was no plunder available." },
  deadMansDrawActionGhallegarAnchor: { fa: "قلاب Ghallegar از خودش و کارت بازی‌شده محافظت می‌کند، حتی اگر همان نوبت بترکی.", en: "Ghallegar's Hook protects itself and the card it plays, even if you bust that turn." },
  deadMansDrawActionScurvyPete: { fa: "Scurvy Pete فعال شد: باید یکی از کارت‌های بالای ستون‌های خودت را دور بیندازی.", en: "Scurvy Pete triggered Misfire: discard one of your own top cards." },
  deadMansDrawActionBlackBonnie: { fa: "Black Bonnie قبل از ضربهٔ شمشیر، یک کراکن را وارد ناحیهٔ گنج کرد.", en: "Black Bonnie forced a Kraken into the treasure area before the Sword strike." },
  deadMansDrawActionSirLovesword: { fa: "Sir Lovesword سکه را بلافاصله از دستهٔ کشیدن بانک کرد.", en: "Sir Lovesword banked a Coin immediately from the draw pile." },
  deadMansDrawActionMadamBust: { fa: "ترکیدی! Madam Margot کارت‌های سوخته را برای خودش بانک کرد.", en: "Bust! Madam Margot banked the busted treasure." },
  deadMansDrawActionGunnieBlast: { fa: "توپ Gunnie کل ستون {{suit}} را منفجر کرد.", en: "Pistol blasted the entire {{suit}} stack." },
  deadMansDrawActionMisfireDiscarded: { fa: "Misfire باعث شد {{suit}} خودت را دور بیندازی.", en: "Misfire discarded your {{suit}}." },
  deadMansDrawEffectBadgeastrolabe: { fa: "چشم", en: "Eye" },
  deadMansDrawEffectBadgepistol: { fa: "توپ", en: "Cannon" },
  deadMansDrawEffectBadgedagger: { fa: "شمشیر", en: "Sword" },
  deadMansDrawEffectBadgehorseshoe: { fa: "قلاب", en: "Hook" },
  deadMansDrawEffectBadgemap: { fa: "نقشه", en: "Map" },
  deadMansDrawEffectBadgemisfire: { fa: "پس‌زدگی", en: "Misfire" },
  deadMansDrawTutorialLabel: { fa: "آموزش کامل", en: "Full tutorial" },
  deadMansDrawTutorialTitle: { fa: "آموزش مرحله‌به‌مرحلهٔ Dead Man's Draw", en: "Step-by-step Dead Man's Draw tutorial" },
  deadMansDrawTutorialIntro: { fa: "اگر اولین بار است بازی می‌کنی، این ۸ مرحله تو را از شروع بازی تا امتیازگیری نهایی جلو می‌برد. قدرت‌های ویژه هم داخل همین آموزش آمده‌اند.", en: "If this is your first game, these 8 steps take you from setup to final scoring. The special powers are included inside the tutorial too." },
  deadMansDrawTutorialStep1Title: { fa: "هدف بازی", en: "Game goal" },
  deadMansDrawTutorialStep1Body: { fa: "هدف این است که در پایان بازی، بالاترین مجموعِ کارت بالایی هر ستون خال را داشته باشی. فقط بالاترین کارت هر خال امتیاز می‌دهد، نه جمع همهٔ کارت‌های آن ستون.", en: "Your goal is to finish with the highest total of the top card in each suit stack. Only the top card in each suit scores, not the whole stack." },
  deadMansDrawTutorialStep2Title: { fa: "شروع بازی", en: "Setup" },
  deadMansDrawTutorialStep2Body: { fa: "در شروع، هر بازیکن دو قدرت رو می‌بیند و یکی را برای کل بازی نگه می‌دارد. اگر Madam Margot را برداری، باید همان اول یک حریف را علامت بزنی.", en: "At the start, each player sees 2 face-up powers and keeps 1 for the whole game. If you take Madam Margot, you must mark one opponent right away." },
  deadMansDrawTutorialStep3Title: { fa: "شروع نوبت", en: "Start of a turn" },
  deadMansDrawTutorialStep3Body: { fa: "در نوبتت یا یک کارت جدید رو می‌کنی یا اگر ناحیهٔ گنج امن است، همان حالا آن را جمع می‌کنی. هر کارت رو شده تا وقتی ترکیده نشوی، در ناحیهٔ گنج می‌ماند.", en: "On your turn, either reveal a new card or, if your treasure area is safe, collect it now. Revealed cards stay in the treasure area until you either bank them or bust." },
  deadMansDrawTutorialStep4Title: { fa: "اگر دوباره همان خال بیاید", en: "What causes a bust" },
  deadMansDrawTutorialStep4Body: { fa: "اگر خالی رو شود که از همان خال قبلا در ناحیهٔ گنج داری، می‌ترکی. کارت‌های نجات‌یافته با Carpet یا Ghallegar می‌مانند و بقیه به پشتهٔ سوخته می‌روند؛ مگر Madam Margot آن‌ها را بدزدد.", en: "If you reveal a suit that is already in your treasure area, you bust. Cards saved by Carpet or Ghallegar stay with you, and the rest go to the burn pile unless Madam Margot steals them." },
  deadMansDrawTutorialStep5Title: { fa: "اثر خال‌ها", en: "Suit effects" },
  deadMansDrawTutorialStep5Body: { fa: "Eye بالا را می‌بیند، Cannon از ستون حریف کم می‌کند، Sword می‌دزدد، Hook از بانک خودت بازی می‌کند، Map از پشتهٔ سوخته برمی‌گرداند، Kraken کارت‌های اجباری اضافه می‌کشد، Coin امتیاز مستقیم است و Chest + Key جایزه می‌دهد.", en: "Eye lets you peek, Cannon removes from an opponent's stack, Sword steals, Hook plays from your own bank, Map recovers from the burn pile, Kraken forces extra draws, Coin is raw score, and Chest + Key gives a bonus." },
  deadMansDrawTutorialStep6Title: { fa: "چه وقت جمع کنی", en: "When to collect" },
  deadMansDrawTutorialStep6Body: { fa: "هر وقت احساس کردی ریسک بالا رفته، گنج رو شده را جمع کن. همهٔ کارت‌های ناحیهٔ گنج به ستون‌های خال بانک تو می‌روند و بعد نوبت نفر بعدی شروع می‌شود.", en: "Whenever the risk feels too high, collect the revealed treasure. Every card in the treasure area moves to your suit stacks, then the next player starts." },
  deadMansDrawTutorialStep7Title: { fa: "Chest + Key و پشتهٔ سوخته", en: "Chest + Key and the burn pile" },
  deadMansDrawTutorialStep7Body: { fa: "اگر در همان نوبت هم Chest و هم Key داشته باشی، بعد از جمع کردن گنج، به اندازهٔ تعداد کارت‌های همان نوبت کارت جایزه می‌گیری. معمولا این کارت‌ها از پشتهٔ سوخته می‌آیند، اما Le Corsaire آن‌ها را از بالای ستون‌های حریف‌ها غارت می‌کند.", en: "If the same haul contains both Chest and Key, you gain bonus cards equal to the number of cards in that haul. Normally those cards come from the burn pile, but Le Corsaire plunders them from the top of opponents' stacks instead." },
  deadMansDrawTutorialStep8Title: { fa: "قدرت‌های ویژه", en: "Special powers" },
  deadMansDrawTutorialStep8Body: { fa: "این ۹ قدرت، بازی پایه را تغییر می‌دهند. قبل از فشار دادن برای کارت بعدی، حتما نگاه کن چه قدرتی روی میز فعال است، چون بعضی از آن‌ها هجومی هستند و بعضی دفاعی.", en: "These 9 powers bend the base game in different ways. Before pushing your luck, check which powers are active, because some are offensive and others are defensive." },
} as const;
export type TranslationKey = keyof typeof translations;

// مقادیر جایگزینی برای {{variable}}
type InterpolationValues = Record<string, string | number>;

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: TranslationKey, values?: InterpolationValues) => string;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("splendor-lang");
    return saved === "en" || saved === "fa" ? saved : "fa";
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("splendor-lang", l);
  }, []);
const t = useCallback(
  (key: TranslationKey, values?: InterpolationValues): string => {
    const entry = translations[key];
    if (!entry) return key;

    let template = entry[lang] ?? entry.fa ?? "";

    if (values) {
      Object.entries(values).forEach(([k, v]) => {
        const re = new RegExp(`{{\\s*${k}\\s*}}`, "g");
        template = template.replace(re, String(v));
      });
    }

    return template;
  },
  [lang],
);

  const dir = lang === "fa" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
