import type { Card, GameState, GemType, TokenType } from "@/lib/gameData";
import type { Phase } from "@/pages/game/gamePageUtils";

export type SplendorGameSceneProps = {
  dir: "ltr" | "rtl";
  backgroundImage: string;
  gameMode: "local" | "ai" | "online";
  phase: Phase;
  lang: string;
  t: (key: string, values?: Record<string, string | number>) => string;
  gameTitle: string;
  state: GameState;
  currentPlayer: GameState["players"][number];
  humanPlayerCount: number;
  turnSecondsLeft: number;
  getPlayerDisplayName: (index: number) => string;
  isCurrentPlayerMe: () => boolean;
  isAIPlayer: (index: number) => boolean;
  onShowQuickRules: () => void;
  onExit: () => void;
  socket: any;
  roomId: string;
  playerId: string;
  playerName: string;
  roomPlayers: Record<string, any>;
  selectedCard: Card | null;
  isReserved: boolean;
  showQuickRules: boolean;
  showExitConfirm: boolean;
  showRematchRequest: boolean;
  waitingForRematch: boolean;
  turnWarning: string;
  systemNotice: string;
  stateCurrentPlayerIndex: number;
  onCloseQuickRules: () => void;
  onCancelCardAction: () => void;
  onBuyCard: () => void;
  onReserveCard: () => void;
  onLeaveGame: () => void;
  onCloseExitConfirm: (open: boolean) => void;
  onCloseRematchRequest: (open: boolean) => void;
  onCloseWaitingRematch: (open: boolean) => void;
  onDeclineRematch: () => void;
  onAcceptRematch: () => void;
  onPlayAgain: () => void;
  onMenu: () => void;
  panelCount: number;
  tempPoolDisplay: Record<TokenType, number> | null;
  selectedGems: GemType[];
  boardSelectedCard: Card | null;
  handleReturnToken: (token: TokenType) => void;
  handleReserveDeck: (level: 1 | 2 | 3) => void;
  handleCardClick: (card: Card) => void;
  handleGemClick: (gem: GemType) => void;
  handleConfirmTokens: () => void;
  handleCancel: () => void;
  backCardsByLevel: Record<1 | 2 | 3, string>;
};
